### ISSUE TITLE
"Au Ra" Race/Gender is now "6"

### ISSUE THREAD

**Issue by Crakila** [XIVStats/XIVStats-Gatherer-Ruby#1]
In the latest Lodestone update, it would seem that the `Au Ra` name for the Race has been changed.

The chart on ffxivcensus.com is now showing as `6`

https://github.com/XIVStats/XIVStats-Gatherer-Ruby/blob/f84165facca818cd03edb80ce18c31a27386fb36/xiv_stats.rb#L70

`race2 = 'Au Ra'` may now only need to be escaped `race2 = 'Au\Ra'`

**Comment by Pricetx** [comment]
That site is actually just a static copy from when the census was last run, which was quite a while ago, and the problem then was to do with pulling the data from the database, rather than inserting it in Ruby. I need to look at getting this script working again, which i'll aim to do this week. I'll leave this issue open though until I confirm everything is working again.
